import { USER_ROLES } from "../auth/auth.types";

export const ROLE_ACCESS = {
  DASHBOARD: [USER_ROLES.ADMIN, USER_ROLES.MANAGER, USER_ROLES.USER],
  ADD_PROJECT: [USER_ROLES.ADMIN],
  ADD_USER: [USER_ROLES.ADMIN],
  WORKFLOW_EDIT: [USER_ROLES.ADMIN, USER_ROLES.MANAGER, USER_ROLES.USER],
  WORKFLOW_APPROVE: [USER_ROLES.MANAGER],
};
